export default [
    {   
        exercise: 'Pullups',
        type: 'body weight',
        amount: '',
        reps: '10',
        sets: '3',
        rest: '60',
    },
    {   
        exercise: 'Pushups',
        type: 'body weight',
        amount: '',
        reps: '10',
        sets: '3',
        rest: '60',
    },
    {   
        exercise: 'Bicep Curls',
        type: 'kgs',
        amount: '15',
        reps: '10',
        sets: '3',
        rest: '60',
    },
    {   
        exercise: 'Tricep Cable Extensions',
        type: 'resistance',
        amount: '10',
        reps: '10',
        sets: '3',
        rest: '60',
    },
    {   
        exercise: 'Squats',
        type: 'kgs',
        amount: '100',
        reps: '8',
        sets: '5',
        rest: '60',
    },
    {   
        exercise: 'Abs',
        type: 'body weight',
        amount: '',
        reps: '10',
        sets: '3',
        rest: '60',
    },
    {   
        exercise: 'Leg Curls',
        type: 'lbs',
        amount: '75',
        reps: '10',
        sets: '3',
        rest: '60',
    },
    {   
        exercise: 'Calf Raises',
        type: 'kgs',
        amount: '10',
        reps: '10',
        sets: '3',
        rest: '60',
    }
]